FROM jenkins/jenkins:lts

USER root

# Instalar Python 3.11 e Docker CLI
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv docker.io && \
    usermod -aG docker jenkins

# Criar link python → python3
RUN ln -s /usr/bin/python3 /usr/bin/python

USER jenkins
